/**
 * قاعدة البيانات المرجعية للتقسيم الإداري لجمهورية مصر العربية
 * مُعتمدة على التقسيمات الرسمية للجهاز المركزي للتعبئة العامة والإحصاء (CAPMAS)
 */

import { Country, AdministrativeUnit } from '../../types/location.ts';

export const EGYPT_COUNTRY: Country = {
  id: 1,
  code: 'EG',
  nameAr: 'جمهورية مصر العربية',
  nameEn: 'Arab Republic of Egypt',
  defaultTimezone: 'Africa/Cairo',
  isDefault: true,
  isActive: true,
};

export const COUNTRIES_LIST: Country[] = [EGYPT_COUNTRY];

/**
 * قائمة محافظات جمهورية مصر العربية الـ 27
 */
export const EGYPT_GOVERNORATES: AdministrativeUnit[] = [
  { id: 1, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'GZ', nameAr: 'الجيزة', nameEn: 'Giza', postalCode: '12511', latitude: 30.0131, longitude: 31.2089, isActive: true, sortOrder: 1 },
  { id: 2, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'CAI', nameAr: 'القاهرة', nameEn: 'Cairo', postalCode: '11511', latitude: 30.0444, longitude: 31.2357, isActive: true, sortOrder: 2 },
  { id: 3, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'ALX', nameAr: 'الإسكندرية', nameEn: 'Alexandria', postalCode: '21500', latitude: 31.2001, longitude: 29.9187, isActive: true, sortOrder: 3 },
  { id: 4, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'QLY', nameAr: 'القليوبية', nameEn: 'Qalyubia', postalCode: '13511', latitude: 30.4591, longitude: 31.1786, isActive: true, sortOrder: 4 },
  { id: 5, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'DKH', nameAr: 'الدقهلية', nameEn: 'Dakahlia', postalCode: '35511', latitude: 31.0409, longitude: 31.3785, isActive: true, sortOrder: 5 },
  { id: 6, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'SHR', nameAr: 'الشرقية', nameEn: 'Sharqia', postalCode: '44511', latitude: 30.5877, longitude: 31.5020, isActive: true, sortOrder: 6 },
  { id: 7, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'GHB', nameAr: 'الغربية', nameEn: 'Gharbia', postalCode: '31511', latitude: 30.7885, longitude: 31.0019, isActive: true, sortOrder: 7 },
  { id: 8, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'MNF', nameAr: 'المنوفية', nameEn: 'Monufia', postalCode: '32511', latitude: 30.5972, longitude: 30.9876, isActive: true, sortOrder: 8 },
  { id: 9, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'BHR', nameAr: 'البحيرة', nameEn: 'Beheira', postalCode: '22511', latitude: 31.0379, longitude: 30.4689, isActive: true, sortOrder: 9 },
  { id: 10, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'KFS', nameAr: 'كفر الشيخ', nameEn: 'Kafr El-Sheikh', postalCode: '33511', latitude: 31.1107, longitude: 30.9388, isActive: true, sortOrder: 10 },
  { id: 11, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'DMT', nameAr: 'دمياط', nameEn: 'Damietta', postalCode: '34511', latitude: 31.4175, longitude: 31.8144, isActive: true, sortOrder: 11 },
  { id: 12, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'PTS', nameAr: 'بورسعيد', nameEn: 'Port Said', postalCode: '42511', latitude: 31.2653, longitude: 32.3019, isActive: true, sortOrder: 12 },
  { id: 13, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'ISM', nameAr: 'الإسماعيلية', nameEn: 'Ismailia', postalCode: '41511', latitude: 30.5965, longitude: 32.2715, isActive: true, sortOrder: 13 },
  { id: 14, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'SUZ', nameAr: 'السويس', nameEn: 'Suez', postalCode: '43511', latitude: 29.9668, longitude: 32.5498, isActive: true, sortOrder: 14 },
  { id: 15, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'FYM', nameAr: 'الفيوم', nameEn: 'Faiyum', postalCode: '63511', latitude: 29.3084, longitude: 30.8428, isActive: true, sortOrder: 15 },
  { id: 16, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'BNS', nameAr: 'بني سويف', nameEn: 'Beni Suef', postalCode: '62511', latitude: 29.0661, longitude: 31.0994, isActive: true, sortOrder: 16 },
  { id: 17, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'MNY', nameAr: 'المنيا', nameEn: 'Minya', postalCode: '61511', latitude: 28.1099, longitude: 30.7503, isActive: true, sortOrder: 17 },
  { id: 18, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'AST', nameAr: 'أسيوط', nameEn: 'Asyut', postalCode: '71511', latitude: 27.1783, longitude: 31.1859, isActive: true, sortOrder: 18 },
  { id: 19, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'SHG', nameAr: 'سوهاج', nameEn: 'Sohag', postalCode: '82511', latitude: 26.5590, longitude: 31.6957, isActive: true, sortOrder: 19 },
  { id: 20, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'QNA', nameAr: 'قنا', nameEn: 'Qena', postalCode: '83511', latitude: 26.1551, longitude: 32.7160, isActive: true, sortOrder: 20 },
  { id: 21, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'LXR', nameAr: 'الأقصر', nameEn: 'Luxor', postalCode: '85951', latitude: 25.6872, longitude: 32.6396, isActive: true, sortOrder: 21 },
  { id: 22, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'ASN', nameAr: 'أسوان', nameEn: 'Aswan', postalCode: '81511', latitude: 24.0889, longitude: 32.8998, isActive: true, sortOrder: 22 },
  { id: 23, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'RED', nameAr: 'البحر الأحمر', nameEn: 'Red Sea', postalCode: '84511', latitude: 27.2579, longitude: 33.8116, isActive: true, sortOrder: 23 },
  { id: 24, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'WAD', nameAr: 'الوادي الجديد', nameEn: 'New Valley', postalCode: '72511', latitude: 25.4514, longitude: 30.5471, isActive: true, sortOrder: 24 },
  { id: 25, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'MAT', nameAr: 'مطروح', nameEn: 'Matrouh', postalCode: '51511', latitude: 31.3543, longitude: 27.2373, isActive: true, sortOrder: 25 },
  { id: 26, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'SIN', nameAr: 'شمال سيناء', nameEn: 'North Sinai', postalCode: '45511', latitude: 31.1316, longitude: 33.7984, isActive: true, sortOrder: 26 },
  { id: 27, countryId: 1, parentId: null, level: 1, type: 'GOVERNORATE', code: 'SIS', nameAr: 'جنوب سيناء', nameEn: 'South Sinai', postalCode: '46511', latitude: 28.9742, longitude: 33.6190, isActive: true, sortOrder: 27 },
];

/**
 * الوحدات الإدارية التابعة (المراكز، الأحياء، الأقسام، المدن، الشياخات، المناطق)
 */
export const EGYPT_ADMINISTRATIVE_UNITS: AdministrativeUnit[] = [
  // ==========================================
  // 1. محافظة الجيزة (Governorate ID: 1) - المستويات الإدارية
  // ==========================================

  // الأحياء والمراكز الرئيسية في الجيزة (Level 2)
  {
    id: 101,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'DISTRICT',
    code: 'GZ-HRM',
    nameAr: 'حي الهرم',
    nameEn: 'Al-Haram District',
    postalCode: '12555',
    latitude: 29.9972,
    longitude: 31.1524,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 102,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'DISTRICT',
    code: 'GZ-DKI',
    nameAr: 'حي الدقي',
    nameEn: 'Dokki District',
    postalCode: '12311',
    latitude: 30.0385,
    longitude: 31.2124,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 103,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'DISTRICT',
    code: 'GZ-AGZ',
    nameAr: 'حي العجوزة',
    nameEn: 'Agouza District',
    postalCode: '12655',
    latitude: 30.0543,
    longitude: 31.2118,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 104,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'DISTRICT',
    code: 'GZ-BLQ',
    nameAr: 'حي بولاق الدكرور',
    nameEn: 'Boulaq Al-Dakrour District',
    postalCode: '12566',
    latitude: 30.0347,
    longitude: 31.1895,
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 105,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'DISTRICT',
    code: 'GZ-OMR',
    nameAr: 'حي العمرانية',
    nameEn: 'Omraneya District',
    postalCode: '12556',
    latitude: 29.9986,
    longitude: 31.2001,
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 106,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'DISTRICT',
    code: 'GZ-TLB',
    nameAr: 'حي الطالبية',
    nameEn: 'Talbiya District',
    postalCode: '12558',
    latitude: 29.9912,
    longitude: 31.1802,
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 107,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'DISTRICT',
    code: 'GZ-STH',
    nameAr: 'حي جنوب الجيزة',
    nameEn: 'South Giza District',
    postalCode: '12511',
    latitude: 29.9925,
    longitude: 31.2185,
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 108,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'DISTRICT',
    code: 'GZ-NTH',
    nameAr: 'حي شمال الجيزة (إمبابة)',
    nameEn: 'North Giza / Imbaba District',
    postalCode: '12411',
    latitude: 30.0755,
    longitude: 31.2084,
    isActive: true,
    sortOrder: 8,
  },
  {
    id: 109,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'CITY',
    code: 'GZ-OCT',
    nameAr: 'مدينة 6 أكتوبر',
    nameEn: '6th of October City',
    postalCode: '12566',
    latitude: 29.9723,
    longitude: 30.9427,
    isActive: true,
    sortOrder: 9,
  },
  {
    id: 110,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'CITY',
    code: 'GZ-ZYD',
    nameAr: 'مدينة الشيخ زايد',
    nameEn: 'Sheikh Zayed City',
    postalCode: '12588',
    latitude: 30.0528,
    longitude: 30.9814,
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 111,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'MARKAZ',
    code: 'GZ-KRD',
    nameAr: 'مركز ومدينة كرداسة',
    nameEn: 'Kerdasa Markaz',
    postalCode: '12577',
    latitude: 30.0333,
    longitude: 31.1167,
    isActive: true,
    sortOrder: 11,
  },
  {
    id: 112,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'MARKAZ',
    code: 'GZ-OSM',
    nameAr: 'مركز ومدينة أوسيم',
    nameEn: 'Oseem Markaz',
    postalCode: '12918',
    latitude: 30.1235,
    longitude: 31.1354,
    isActive: true,
    sortOrder: 12,
  },
  {
    id: 113,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'MARKAZ',
    code: 'GZ-ABN',
    nameAr: 'مركز ومدينة أبو النمرس',
    nameEn: 'Abu El-Nomros Markaz',
    postalCode: '12932',
    latitude: 29.9142,
    longitude: 31.2289,
    isActive: true,
    sortOrder: 13,
  },
  {
    id: 114,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'MARKAZ',
    code: 'GZ-HWM',
    nameAr: 'مركز ومدينة الحوامدية',
    nameEn: 'El-Hawamdeya Markaz',
    postalCode: '12954',
    latitude: 29.8967,
    longitude: 31.2644,
    isActive: true,
    sortOrder: 14,
  },
  {
    id: 115,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'MARKAZ',
    code: 'GZ-BDR',
    nameAr: 'مركز ومدينة البدرشين',
    nameEn: 'El-Badrasheen Markaz',
    postalCode: '12966',
    latitude: 29.8167,
    longitude: 31.2667,
    isActive: true,
    sortOrder: 15,
  },
  {
    id: 116,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'MARKAZ',
    code: 'GZ-AYT',
    nameAr: 'مركز ومدينة العياط',
    nameEn: 'El-Ayat Markaz',
    postalCode: '12978',
    latitude: 29.6192,
    longitude: 31.2575,
    isActive: true,
    sortOrder: 16,
  },
  {
    id: 117,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'MARKAZ',
    code: 'GZ-SAF',
    nameAr: 'مركز ومدينة الصف',
    nameEn: 'El-Saff Markaz',
    postalCode: '12989',
    latitude: 29.5667,
    longitude: 31.3000,
    isActive: true,
    sortOrder: 17,
  },
  {
    id: 118,
    countryId: 1,
    parentId: 1,
    level: 2,
    type: 'MARKAZ',
    code: 'GZ-ATF',
    nameAr: 'مركز ومدينة أطفيح',
    nameEn: 'Atfeeh Markaz',
    postalCode: '12995',
    latitude: 29.4167,
    longitude: 31.2500,
    isActive: true,
    sortOrder: 18,
  },

  // ----------------------------------------------------
  // مناطق وشياخات حي الهرم (District ID: 101) - Level 3
  // التركيز الأساسي ومقر الجمعية
  // ----------------------------------------------------
  {
    id: 1001,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'SHEIKHA',
    code: 'GZ-HRM-MBK',
    nameAr: 'منشأة البكاري',
    nameEn: 'Munsha\'at Al-Bakkari',
    postalCode: '12555',
    latitude: 30.0125,
    longitude: 31.1412,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 1002,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'SHEIKHA',
    code: 'GZ-HRM-KFR',
    nameAr: 'كفر غطاطي',
    nameEn: 'Kafr Ghatati',
    postalCode: '12555',
    latitude: 30.0051,
    longitude: 31.1328,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 1003,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'SHEIKHA',
    code: 'GZ-HRM-NZS',
    nameAr: 'نزلة السيسي',
    nameEn: 'Nazlet El-Sisi',
    postalCode: '12555',
    latitude: 29.9882,
    longitude: 31.1473,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 1004,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'SHEIKHA',
    code: 'GZ-HRM-NZB',
    nameAr: 'نزلة البطران',
    nameEn: 'Nazlet El-Batran',
    postalCode: '12555',
    latitude: 29.9854,
    longitude: 31.1421,
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 1005,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'AREA',
    code: 'GZ-HRM-MSH',
    nameAr: 'مشعل',
    nameEn: 'Mashaal',
    postalCode: '12555',
    latitude: 29.9915,
    longitude: 31.1558,
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 1006,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'AREA',
    code: 'GZ-HRM-FSL',
    nameAr: 'شارع فيصل (الملك فيصل)',
    nameEn: 'King Faisal Street Area',
    postalCode: '12555',
    latitude: 30.0041,
    longitude: 31.1685,
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 1007,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'AREA',
    code: 'GZ-HRM-HRM',
    nameAr: 'شارع الأهرام (شارع الهرم)',
    nameEn: 'Al-Ahram Street Area',
    postalCode: '12555',
    latitude: 29.9972,
    longitude: 31.1524,
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 1008,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'AREA',
    code: 'GZ-HRM-ARSH',
    nameAr: 'العريش (شارع العريش)',
    nameEn: 'Al-Areesh',
    postalCode: '12555',
    latitude: 29.9998,
    longitude: 31.1623,
    isActive: true,
    sortOrder: 8,
  },
  {
    id: 1009,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'AREA',
    code: 'GZ-HRM-DYA',
    nameAr: 'محطة ضياء',
    nameEn: 'Diyaa Station Area',
    postalCode: '12555',
    latitude: 30.0018,
    longitude: 31.1712,
    isActive: true,
    sortOrder: 9,
  },
  {
    id: 1010,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'AREA',
    code: 'GZ-HRM-HSN',
    nameAr: 'حسن محمد',
    nameEn: 'Hassan Mohamed',
    postalCode: '12555',
    latitude: 30.0005,
    longitude: 31.1678,
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 1011,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'AREA',
    code: 'GZ-HRM-KOM',
    nameAr: 'الكوم الأخضر',
    nameEn: 'Al-Kom Al-Akhdar',
    postalCode: '12555',
    latitude: 29.9961,
    longitude: 31.1652,
    isActive: true,
    sortOrder: 11,
  },
  {
    id: 1012,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'SHEIKHA',
    code: 'GZ-HRM-KFG',
    nameAr: 'كفر الجبل',
    nameEn: 'Kafr El-Gabal',
    postalCode: '12555',
    latitude: 29.9798,
    longitude: 31.1445,
    isActive: true,
    sortOrder: 12,
  },
  {
    id: 1013,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'AREA',
    code: 'GZ-HRM-WFA',
    nameAr: 'الوفاء والأمل',
    nameEn: 'Al-Wafaa Wal-Amal',
    postalCode: '12555',
    latitude: 29.9912,
    longitude: 31.1601,
    isActive: true,
    sortOrder: 13,
  },
  {
    id: 1014,
    countryId: 1,
    parentId: 101,
    level: 3,
    type: 'AREA',
    code: 'GZ-HRM-TLBF',
    nameAr: 'الطالبية فيصل',
    nameEn: 'Talbiya Faisal',
    postalCode: '12555',
    latitude: 30.0055,
    longitude: 31.1772,
    isActive: true,
    sortOrder: 14,
  },

  // مناطق وشياخات الدقي (District ID: 102)
  { id: 1021, countryId: 1, parentId: 102, level: 3, type: 'AREA', code: 'GZ-DKI-MSH', nameAr: 'ميدان المساحة', nameEn: 'Messaha Square', isActive: true, sortOrder: 1 },
  { id: 1022, countryId: 1, parentId: 102, level: 3, type: 'AREA', code: 'GZ-DKI-MSD', nameAr: 'شارع مصدق', nameEn: 'Mossadak Street', isActive: true, sortOrder: 2 },
  { id: 1023, countryId: 1, parentId: 102, level: 3, type: 'AREA', code: 'GZ-DKI-THR', nameAr: 'شارع التحرير', nameEn: 'Tahrir Street', isActive: true, sortOrder: 3 },
  { id: 1024, countryId: 1, parentId: 102, level: 3, type: 'AREA', code: 'GZ-DKI-BNS', nameAr: 'بين السرايات', nameEn: 'Bain El-Sarayat', isActive: true, sortOrder: 4 },

  // مناطق وشياخات العجوزة والمهندسين (District ID: 103)
  { id: 1031, countryId: 1, parentId: 103, level: 3, type: 'AREA', code: 'GZ-AGZ-MHD', nameAr: 'المهندسين (جامعة الدول)', nameEn: 'Mohandessin', isActive: true, sortOrder: 1 },
  { id: 1032, countryId: 1, parentId: 103, level: 3, type: 'AREA', code: 'GZ-AGZ-AGZ', nameAr: 'ميدان العجوزة والنيل', nameEn: 'Agouza Nile Corniche', isActive: true, sortOrder: 2 },
  { id: 1033, countryId: 1, parentId: 103, level: 3, type: 'AREA', code: 'GZ-AGZ-MTQ', nameAr: 'ميت عقبة', nameEn: 'Meet Okba', isActive: true, sortOrder: 3 },
  { id: 1034, countryId: 1, parentId: 103, level: 3, type: 'AREA', code: 'GZ-AGZ-SHF', nameAr: 'مدينة الصحفيين', nameEn: 'Sahafiyyin City', isActive: true, sortOrder: 4 },

  // مناطق بولاق الدكرور (District ID: 104)
  { id: 1041, countryId: 1, parentId: 104, level: 3, type: 'AREA', code: 'GZ-BLQ-SFT', nameAr: 'صفط اللبن', nameEn: 'Saft El-Laban', isActive: true, sortOrder: 1 },
  { id: 1042, countryId: 1, parentId: 104, level: 3, type: 'AREA', code: 'GZ-BLQ-NHY', nameAr: 'ناهيا', nameEn: 'Nahia', isActive: true, sortOrder: 2 },
  { id: 1043, countryId: 1, parentId: 104, level: 3, type: 'AREA', code: 'GZ-BLQ-THR', nameAr: 'كفر طهرمس', nameEn: 'Kafr Tohormos', isActive: true, sortOrder: 3 },
  { id: 1044, countryId: 1, parentId: 104, level: 3, type: 'AREA', code: 'GZ-BLQ-ABQ', nameAr: 'أبو قتادة', nameEn: 'Abu Qatada', isActive: true, sortOrder: 4 },

  // مناطق العمرانية (District ID: 105)
  { id: 1051, countryId: 1, parentId: 105, level: 3, type: 'AREA', code: 'GZ-OMR-WST', nameAr: 'العمرانية الغربية', nameEn: 'West Omraneya', isActive: true, sortOrder: 1 },
  { id: 1052, countryId: 1, parentId: 105, level: 3, type: 'AREA', code: 'GZ-OMR-EST', nameAr: 'العمرانية الشرقية', nameEn: 'East Omraneya', isActive: true, sortOrder: 2 },
  { id: 1053, countryId: 1, parentId: 105, level: 3, type: 'AREA', code: 'GZ-OMR-SQM', nameAr: 'ساقية مكي', nameEn: 'Saqyet Mekki', isActive: true, sortOrder: 3 },

  // مناطق الطالبية (District ID: 106)
  { id: 1061, countryId: 1, parentId: 106, level: 3, type: 'AREA', code: 'GZ-TLB-KNS', nameAr: 'الكونيسة', nameEn: 'El-Koneisa', isActive: true, sortOrder: 1 },
  { id: 1062, countryId: 1, parentId: 106, level: 3, type: 'AREA', code: 'GZ-TLB-ORB', nameAr: 'شارع العروبة', nameEn: 'Orouba Street', isActive: true, sortOrder: 2 },
  { id: 1063, countryId: 1, parentId: 106, level: 3, type: 'AREA', code: 'GZ-TLB-JBR', nameAr: 'عزبة جبريل', nameEn: 'Ezbet Gebril', isActive: true, sortOrder: 3 },

  // مناطق جنوب الجيزة (District ID: 107)
  { id: 1071, countryId: 1, parentId: 107, level: 3, type: 'AREA', code: 'GZ-STH-MNB', nameAr: 'المنيب', nameEn: 'El-Moneeb', isActive: true, sortOrder: 1 },
  { id: 1072, countryId: 1, parentId: 107, level: 3, type: 'AREA', code: 'GZ-STH-MDS', nameAr: 'ميدان الجيزة ومحطة القطار', nameEn: 'Giza Square', isActive: true, sortOrder: 2 },
  { id: 1073, countryId: 1, parentId: 107, level: 3, type: 'AREA', code: 'GZ-STH-JZR', nameAr: 'جزيرة الذهب', nameEn: 'Geziret El-Dahab', isActive: true, sortOrder: 3 },

  // مناطق شمال الجيزة / إمبابة (District ID: 108)
  { id: 1081, countryId: 1, parentId: 108, level: 3, type: 'AREA', code: 'GZ-NTH-MNR', nameAr: 'المنيرة الغربية والشرقية', nameEn: 'El-Moneera', isActive: true, sortOrder: 1 },
  { id: 1082, countryId: 1, parentId: 108, level: 3, type: 'AREA', code: 'GZ-NTH-BSH', nameAr: 'بشتيل', nameEn: 'Bashteel', isActive: true, sortOrder: 2 },
  { id: 1083, countryId: 1, parentId: 108, level: 3, type: 'AREA', code: 'GZ-NTH-KTS', nameAr: 'مدينة العمال وكيت كات', nameEn: 'Kit Kat & Ommal', isActive: true, sortOrder: 3 },

  // مناطق مدينة 6 أكتوبر (City ID: 109)
  { id: 1091, countryId: 1, parentId: 109, level: 3, type: 'AREA', code: 'GZ-OCT-MTM', nameAr: 'الحي المتميز', nameEn: 'Distinguished District', isActive: true, sortOrder: 1 },
  { id: 1092, countryId: 1, parentId: 109, level: 3, type: 'AREA', code: 'GZ-OCT-H01', nameAr: 'الأحياء السكنية (1 إلى 12)', nameEn: 'Residential Districts 1-12', isActive: true, sortOrder: 2 },
  { id: 1093, countryId: 1, parentId: 109, level: 3, type: 'AREA', code: 'GZ-OCT-HDQ', nameAr: 'حدائق أكتوبر', nameEn: 'October Gardens', isActive: true, sortOrder: 3 },
  { id: 1094, countryId: 1, parentId: 109, level: 3, type: 'AREA', code: 'GZ-OCT-TSN', nameAr: 'التوسعات الشمالية', nameEn: 'Northern Expansions', isActive: true, sortOrder: 4 },

  // مناطق مدينة الشيخ زايد (City ID: 110)
  { id: 1101, countryId: 1, parentId: 110, level: 3, type: 'AREA', code: 'GZ-ZYD-H01', nameAr: 'الأحياء السكنية من 1 إلى 16', nameEn: 'Residential Districts 1-16', isActive: true, sortOrder: 1 },
  { id: 1102, countryId: 1, parentId: 110, level: 3, type: 'AREA', code: 'GZ-ZYD-THR', nameAr: 'الثورة الخضراء', nameEn: 'Green Revolution Area', isActive: true, sortOrder: 2 },

  // قرى ومناطق مركز كرداسة (Markaz ID: 111)
  { id: 1111, countryId: 1, parentId: 111, level: 3, type: 'VILLAGE', code: 'GZ-KRD-ABR', nameAr: 'أبورواش', nameEn: 'Abu Rawash', isActive: true, sortOrder: 1 },
  { id: 1112, countryId: 1, parentId: 111, level: 3, type: 'VILLAGE', code: 'GZ-KRD-BRK', nameAr: 'برك الخيام', nameEn: 'Bereik El-Khayyam', isActive: true, sortOrder: 2 },
  { id: 1113, countryId: 1, parentId: 111, level: 3, type: 'VILLAGE', code: 'GZ-KRD-MTM', nameAr: 'المعتمدية', nameEn: 'Al-Moatamadeya', isActive: true, sortOrder: 3 },
  { id: 1114, countryId: 1, parentId: 111, level: 3, type: 'VILLAGE', code: 'GZ-KRD-KHK', nameAr: 'كفر حكيم', nameEn: 'Kafr Hakim', isActive: true, sortOrder: 4 },

  // ==========================================
  // 2. محافظة القاهرة (Governorate ID: 2) - المستويات الإدارية
  // ==========================================
  { id: 201, countryId: 1, parentId: 2, level: 2, type: 'DISTRICT', code: 'CAI-MSR', nameAr: 'حي مصر الجديدة', nameEn: 'Heliopolis District', isActive: true, sortOrder: 1 },
  { id: 202, countryId: 1, parentId: 2, level: 2, type: 'DISTRICT', code: 'CAI-NSR', nameAr: 'حي مدينة نصر', nameEn: 'Nasr City District', isActive: true, sortOrder: 2 },
  { id: 203, countryId: 1, parentId: 2, level: 2, type: 'DISTRICT', code: 'CAI-MAD', nameAr: 'حي المعادي', nameEn: 'Maadi District', isActive: true, sortOrder: 3 },
  { id: 204, countryId: 1, parentId: 2, level: 2, type: 'DISTRICT', code: 'CAI-HLW', nameAr: 'حي حلوان', nameEn: 'Helwan District', isActive: true, sortOrder: 4 },
  { id: 205, countryId: 1, parentId: 2, level: 2, type: 'DISTRICT', code: 'CAI-ZNB', nameAr: 'حي السيدة زينب', nameEn: 'Sayeda Zeinab District', isActive: true, sortOrder: 5 },
  { id: 206, countryId: 1, parentId: 2, level: 2, type: 'DISTRICT', code: 'CAI-TAG', nameAr: 'القاهرة الجديدة (التجمع الخامس)', nameEn: 'New Cairo / 5th Settlement', isActive: true, sortOrder: 6 },
  { id: 207, countryId: 1, parentId: 2, level: 2, type: 'DISTRICT', code: 'CAI-SHB', nameAr: 'حي شبرا', nameEn: 'Shubra District', isActive: true, sortOrder: 7 },
  { id: 208, countryId: 1, parentId: 2, level: 2, type: 'DISTRICT', code: 'CAI-ZYT', nameAr: 'حي الزيتون', nameEn: 'Zeitoun District', isActive: true, sortOrder: 8 },

  // مناطق القاهرة (Level 3)
  { id: 2011, countryId: 1, parentId: 201, level: 3, type: 'AREA', code: 'CAI-MSR-KRB', nameAr: 'الكوربة وروكسي', nameEn: 'Korba & Roxy', isActive: true, sortOrder: 1 },
  { id: 2021, countryId: 1, parentId: 202, level: 3, type: 'AREA', code: 'CAI-NSR-MKR', nameAr: 'شارع مكرم عبيد وعباس العقاد', nameEn: 'Makram Ebeid & Abbas El Akkad', isActive: true, sortOrder: 1 },
  { id: 2031, countryId: 1, parentId: 203, level: 3, type: 'AREA', code: 'CAI-MAD-DGL', nameAr: 'دجلة وثكنات المعادي', nameEn: 'Degla & Thakanat El Maadi', isActive: true, sortOrder: 1 },
  { id: 2061, countryId: 1, parentId: 206, level: 3, type: 'AREA', code: 'CAI-TAG-005', nameAr: 'التجمع الخامس (شارع التسعين)', nameEn: '90th Street Area', isActive: true, sortOrder: 1 },

  // ==========================================
  // 3. محافظة الإسكندرية (Governorate ID: 3)
  // ==========================================
  { id: 301, countryId: 1, parentId: 3, level: 2, type: 'DISTRICT', code: 'ALX-MN1', nameAr: 'حي المنتزه أول', nameEn: 'Montaza 1 District', isActive: true, sortOrder: 1 },
  { id: 302, countryId: 1, parentId: 3, level: 2, type: 'DISTRICT', code: 'ALX-MN2', nameAr: 'حي المنتزه ثان', nameEn: 'Montaza 2 District', isActive: true, sortOrder: 2 },
  { id: 303, countryId: 1, parentId: 3, level: 2, type: 'DISTRICT', code: 'ALX-EST', nameAr: 'حي شرق الإسكندرية', nameEn: 'East District', isActive: true, sortOrder: 3 },
  { id: 304, countryId: 1, parentId: 3, level: 2, type: 'DISTRICT', code: 'ALX-MID', nameAr: 'حي وسط الإسكندرية', nameEn: 'Middle District', isActive: true, sortOrder: 4 },
  { id: 305, countryId: 1, parentId: 3, level: 2, type: 'DISTRICT', code: 'ALX-AGM', nameAr: 'حي العجمي', nameEn: 'Agami District', isActive: true, sortOrder: 5 },

  // مناطق الإسكندرية (Level 3)
  { id: 3011, countryId: 1, parentId: 301, level: 3, type: 'AREA', code: 'ALX-MN1-MYM', nameAr: 'ميامي وسيدي بشر', nameEn: 'Miami & Sidi Bishr', isActive: true, sortOrder: 1 },
  { id: 3031, countryId: 1, parentId: 303, level: 3, type: 'AREA', code: 'ALX-EST-SMH', nameAr: 'سموحة وسيدي جابر', nameEn: 'Smouha & Sidi Gaber', isActive: true, sortOrder: 1 },
  { id: 3041, countryId: 1, parentId: 304, level: 3, type: 'AREA', code: 'ALX-MID-MHT', nameAr: 'محطة الرمل والشاطبي', nameEn: 'Raml Station & Shatby', isActive: true, sortOrder: 1 },

  // ==========================================
  // باقي المحافظات: مراكزها ومدنها الحيوية
  // ==========================================
  // القليوبية (ID: 4)
  { id: 401, countryId: 1, parentId: 4, level: 2, type: 'CITY', code: 'QLY-BNH', nameAr: 'مدينة بنها', nameEn: 'Banha', isActive: true, sortOrder: 1 },
  { id: 402, countryId: 1, parentId: 4, level: 2, type: 'DISTRICT', code: 'QLY-SHB', nameAr: 'شبرا الخيمة', nameEn: 'Shubra El-Kheima', isActive: true, sortOrder: 2 },
  { id: 403, countryId: 1, parentId: 4, level: 2, type: 'MARKAZ', code: 'QLY-QLB', nameAr: 'مركز قليوب', nameEn: 'Qalyub', isActive: true, sortOrder: 3 },
  { id: 404, countryId: 1, parentId: 4, level: 2, type: 'CITY', code: 'QLY-OBR', nameAr: 'مدينة العبور', nameEn: 'Obour City', isActive: true, sortOrder: 4 },

  // الدقهلية (ID: 5)
  { id: 501, countryId: 1, parentId: 5, level: 2, type: 'CITY', code: 'DKH-MNS', nameAr: 'مدينة المنصورة', nameEn: 'Mansoura', isActive: true, sortOrder: 1 },
  { id: 502, countryId: 1, parentId: 5, level: 2, type: 'MARKAZ', code: 'DKH-MTG', nameAr: 'مركز ميت غمر', nameEn: 'Mit Ghamr', isActive: true, sortOrder: 2 },
  { id: 503, countryId: 1, parentId: 5, level: 2, type: 'MARKAZ', code: 'DKH-SNB', nameAr: 'مركز السنبلاوين', nameEn: 'Sinbillawin', isActive: true, sortOrder: 3 },

  // الشرقية (ID: 6)
  { id: 601, countryId: 1, parentId: 6, level: 2, type: 'CITY', code: 'SHR-ZGZ', nameAr: 'مدينة الزقازيق', nameEn: 'Zagazig', isActive: true, sortOrder: 1 },
  { id: 602, countryId: 1, parentId: 6, level: 2, type: 'CITY', code: 'SHR-RAM', nameAr: 'مدينة العاشر من رمضان', nameEn: '10th of Ramadan City', isActive: true, sortOrder: 2 },
  { id: 603, countryId: 1, parentId: 6, level: 2, type: 'MARKAZ', code: 'SHR-BLB', nameAr: 'مركز بلبيس', nameEn: 'Belbeis', isActive: true, sortOrder: 3 },

  // الغربية (ID: 7)
  { id: 701, countryId: 1, parentId: 7, level: 2, type: 'CITY', code: 'GHB-TNT', nameAr: 'مدينة طنطا', nameEn: 'Tanta', isActive: true, sortOrder: 1 },
  { id: 702, countryId: 1, parentId: 7, level: 2, type: 'CITY', code: 'GHB-MHL', nameAr: 'مدينة المحلة الكبرى', nameEn: 'El-Mahalla El-Kubra', isActive: true, sortOrder: 2 },
  { id: 703, countryId: 1, parentId: 7, level: 2, type: 'MARKAZ', code: 'GHB-ZFT', nameAr: 'مركز زفتى', nameEn: 'Zefta', isActive: true, sortOrder: 3 },

  // المنوفية (ID: 8)
  { id: 801, countryId: 1, parentId: 8, level: 2, type: 'CITY', code: 'MNF-SHB', nameAr: 'مدينة شبين الكوم', nameEn: 'Shibin El-Kom', isActive: true, sortOrder: 1 },
  { id: 802, countryId: 1, parentId: 8, level: 2, type: 'CITY', code: 'MNF-SAD', nameAr: 'مدينة السادات', nameEn: 'Sadat City', isActive: true, sortOrder: 2 },
  { id: 803, countryId: 1, parentId: 8, level: 2, type: 'MARKAZ', code: 'MNF-ASH', nameAr: 'مركز أشمون', nameEn: 'Ashmoun', isActive: true, sortOrder: 3 },

  // الفيوم (ID: 15)
  { id: 1501, countryId: 1, parentId: 15, level: 2, type: 'CITY', code: 'FYM-FYM', nameAr: 'مدينة الفيوم', nameEn: 'Faiyum City', isActive: true, sortOrder: 1 },
  { id: 1502, countryId: 1, parentId: 15, level: 2, type: 'MARKAZ', code: 'FYM-SNS', nameAr: 'مركز سنورس', nameEn: 'Sinnuris', isActive: true, sortOrder: 2 },

  // بني سويف (ID: 16)
  { id: 1601, countryId: 1, parentId: 16, level: 2, type: 'CITY', code: 'BNS-BNS', nameAr: 'مدينة بني سويف', nameEn: 'Beni Suef City', isActive: true, sortOrder: 1 },
  { id: 1602, countryId: 1, parentId: 16, level: 2, type: 'MARKAZ', code: 'BNS-WAS', nameAr: 'مركز الواسطى', nameEn: 'El-Wasta', isActive: true, sortOrder: 2 },
];
